Repository quassel/quassel, pull requests merged in 2019-08, with the labels that each got.

#480 cmake: fix build on MSYS2
  CMakeLists.txt
  cmake/QuasselCompileSettings.cmake
  cmake/QuasselMacros.cmake
Labels: needs rebase

#489 qtui: Set desktop file name
  src/main/monoapplication.cpp
  src/qtui/qtuiapplication.cpp
Labels: ready

#506 Remove debug console and QtScript, which was deprecated with Qt5
  CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/coresession.cpp
  src/core/coresession.h
  src/qtui/CMakeLists.txt
  src/qtui/debugconsole.cpp
  src/qtui/debugconsole.h
  src/qtui/debugconsole.ui
Labels: ready

#509 cmake: Don't needlessly sync translations
  po/CMakeLists.txt
Labels: bug, ready
